### ISSUE TITLE
Unsupported file-type: Unspecified

### ISSUE THREAD

**Issue by Brokemia** [ram-nat/CyHeif#2]
Hi, I'm trying to use this project to save some PIL images as .heic files. However, I'm getting the following error whenever I try:
```
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "server.py", line 16, in upload
    cyheif.write_pil_image(img, b'images/image'+imgFrame.to_bytes(2,'big')+b'.heic')
  File "heif\heif.pyx", line 357, in cyheif.write_pil_image
  File "heif\heif.pyx", line 298, in cyheif.HeifImageHandle.get_image_from_rgb_bytes
  File "heif\heif.pyx", line 78, in cyheif.HeifEncoder.__cinit__
  File "heif\heif.pyx", line 27, in cyheif.HeifError.__cinit__
Exception: Heif Error - Message: b'Unsupported file-type: Unspecified', Code: 3, Sub Code: 0
```
I'm not really clear what the cause could be, do you have any idea?

**Comment by Brokemia** [comment]
I've found the issue. I didn't have x265 installed.
